### ISSUE TITLE
Don't declare states/inputs up front

### ISSUE THREAD

**Issue by makaimann** [upscale-project/cosa2#12]
There are often scenarios where an input needs to be "promoted" to a state variable based on some added constraints (important for soundness!). This is much easier to do if they are not declared beforehand, but instead marked as states later.

**Comment by makaimann** [comment]
Addressing this with https://github.com/upscale-project/cosa2/pull/17. Decided to still declare them up front.

**Comment by ahmed-irfan** [comment]
this can be closed i think

**Comment by makaimann** [comment]
Good catch, this was addressed with https://github.com/upscale-project/cosa2/pull/17
