### ISSUE TITLE
Suggestion to the Yosys Script

### ISSUE THREAD

**Issue by zhanghongce** [upscale-project/cosa2#26]
Hi,

I was thinking maybe it is helpful to mention the `sim` command
in the example yosys script, because sometimes, people may need to
use that to drive the reset pin to get the reset state for formal analysis.

I usually use it in the following way:
`sim -clock %clockpin% -reset %resetpin% -n 1 -w %top_module%`

There are also other useful options (like nreset, zinit, rstlen) from the Yosys's help message

Thanks
Hongce

**Comment by makaimann** [comment]
Hi Hongce,

Thanks for the suggestion! I hadn't used that before -- I must have missed it. Thanks for pointing that out! So you run this before writing to btor and it sets the initial state appropriately? Will it toggle the clock for you also?

**Comment by zhanghongce** [comment]
Hi Makai,

> So you run this before writing to btor and it sets the initial state appropriately?

Yes, I added it at the very last (after those `flatten`/`setundef` stuffs
and before `write_btor`) and it seems working okay so far.

The `-w` option there tells yosys to set the initial state according
to the simulation.

> Will it toggle the clock for you also?

I'm not sure actually (especially for asynchronous circuit).
I think for synchronous circuit it will tick the clock, so everything will
run step-by-step, but as those designs don't read the clock signal directly
 (except used in the sensitively list), I don't know if it will toggle.
Let me give it a try.

**Comment by zhanghongce** [comment]
Okay, at least, I think `sim` probably does not work well with `clk2fflogic`.
`sim` does not handle the `$ff` module created by `clk2fflogic`.

**Comment by makaimann** [comment]
Added with https://github.com/upscale-project/cosa2/commit/69467a58135ad058b82a6b214c8c71bf22494026. Thanks for pointing this out! Hopefully it can just run before `clk2fflogic`, but even if that doesn't work this is still an extremely useful command.
