### ISSUE TITLE
Build broken with latest smt-switch

### ISSUE THREAD

**Issue by cliffordwolf** [upscale-project/cosa2#35]
Looks like https://github.com/makaimann/smt-switch/commit/48589590a27f8476f76f49daf072c6b98721edb3 broke cosa2 build. This worked as a quick-and-dirty work-around for me:

```
diff --git a/contrib/setup-smt-switch.sh b/contrib/setup-smt-switch.sh
index e22cde1..694d4ba 100755
--- a/contrib/setup-smt-switch.sh
+++ b/contrib/setup-smt-switch.sh
@@ -51,6 +51,7 @@ if [ ! -d "$DEPS/smt-switch" ]; then
     cd $DEPS
     git clone https://github.com/makaimann/smt-switch
     cd smt-switch
+    git checkout -f 48589590~1
     ./contrib/setup-btor.sh
 
     if [[ "$WITH_MSAT" != default ]]; then
```

cc @makaimann

**Comment by makaimann** [comment]
Oops, yes I forgot I hadn't pinned the smt-switch version. Did that with e0cc7d9d43c009ebbf81b4280db348f1e53080d4. Working on a real update now.

**Comment by makaimann** [comment]
Here's the actual fix: https://github.com/upscale-project/cosa2/pull/37
